services:
  frontend:
    build:
      context: project/frontend
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./project/frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    restart: always
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: project/backend
    volumes:
      - ./project/backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    expose: 
      - 8080
    ports:
      - 8080:8080
  mongo:
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017
networks:
  react-express:
  express-mongo: